openapi: 3.0.0
info:
  title: VibeNet API 🗃️
  description: VibeNet system
  version: 1.0.0

servers:
  - url: http://localhost:6060/
    description: local server

paths:
  /api/register:
    post:
      tags:
        - User
      summary: Register a new user
      description: Adds a new user to the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The first name of the user
                  example: "John"
                lastName:
                  type: string
                  description: The last name of the user
                  example: "Doe"
                email:
                  type: string
                  format: email
                  description: The email of the user
                  example: "johndoe@example.com"
                password:
                  type: string
                  format: password
                  description: The password of the user
                  example: "SecurePassword123"
                gender:
                  type: string
                  description: The gender of the user
                  example: "Male"
      responses:
        "201":
          description: User created successfully
        "409":
          description: A user with this email already exists
        "500":
          description: Error creating user
